import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell' });
const page = await browser.newPage({ viewport: { width: 1400, height: 950 } });
const errors = [];
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push('CONSOLE ' + m.text()); });
const shot = async (n) => { await page.screenshot({ path: `/home/claude/touchline/shots/${n}.png` }); console.log('shot', n); };
await page.goto('http://localhost:5173');
await page.waitForTimeout(2500);
await shot('30-start');
await page.click('text=Load game');
await page.waitForTimeout(600);
await shot('31-load');
await page.click('text=Close');
await page.click('text=New career');
await page.waitForTimeout(400);
await page.click('text=Serie A');
await page.click('text=Inter');
await page.fill('input[placeholder="Manager name"]', 'Nacho');
await page.click('text=Manage INT');
await page.waitForTimeout(4000);
await page.click('text=Preview');
await page.waitForTimeout(800);
await shot('32-preview');
await page.click('.sidebar >> text=Home');
await page.waitForTimeout(300);
for (let i = 0; i < 12; i++) {
  if (await page.$('text=Kick off')) break;
  await page.waitForFunction(() => { const el = document.querySelector('.topbar button.primary'); return el && !el.hasAttribute('disabled'); }, null, { timeout: 60000 });
  await page.click('.topbar button.primary');
  await page.waitForTimeout(1200);
}
if (!(await page.$('text=Kick off'))) await page.click('.topbar button.primary');
await page.waitForTimeout(600);
await page.click('text=Kick off');
await page.waitForTimeout(400);
await page.click('text=2D pitch');
await page.click('text=8×');
await page.waitForTimeout(6000);
await shot('33-2d');
// wait for half time modal
await page.waitForSelector('text=Start second half', { timeout: 120000 });
await shot('34-halftime');
await page.click('text=Start second half');
await page.waitForTimeout(4000);
await shot('35-2d-secondhalf');
await page.click('text=Skip to end');
await page.waitForTimeout(800);
const ft = await page.$('text=see report'); if (ft) await ft.click();
await page.waitForTimeout(600);
await page.click('text=Continue');
await page.waitForTimeout(2000);
await page.click('.sidebar >> text=💾');
await page.waitForTimeout(500);
await shot('36-save');
console.log('ERRORS:', errors.length ? errors.join('\n') : 'none');
await browser.close();
